name: crik-server
version: '0.1.0.0'
category: Web
author: Jacob Leach
maintainer: leach.jacob@gmail.com
copyright: ! 'Copyright: (c) 2017 Jacob Leach'
license: UnspecifiedLicense
github: the-adirondacks-project/crik-server
extra-source-files:
- README.md
library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  exposed-modules:
  - API
  - Database.Error
  - Database.Video
  - Database.VideoFile
  - Database.VideoLibrary
  - Types
  - Types.Video
  - Types.VideoFile
  - Types.VideoLibrary
  dependencies:
  - aeson
  - base >=4.7 && <5
  - bytestring
  - postgresql-simple
  - servant
  - text
executables:
  crik-swagger-gen:
    main: Main.hs
    source-dirs: swagger-gen
    default-extensions:
    - OverloadedStrings
    other-extensions:
    - DataKinds
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - aeson-pretty
    - bytestring
    - crik-types
    - base
    - insert-ordered-containers
    - lens
    - servant
    - servant-swagger
    - swagger2
    - text
  crik-server:
    main: Main.hs
    source-dirs: app
    default-extensions:
    - OverloadedStrings
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aeson
    - bytestring
    - base
    - directory
    - lens
    - mtl
    - postgresql-simple
    - servant
    - servant-server
    - servant-swagger
    - swagger2
    - crik-server
    - text
    - wai
    - wai-extra
    - warp
tests:
  crik-server-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - crik-server

